### ISSUE TITLE
Use view instead of parsing response

### ISSUE THREAD

**Issue by daris** [simonstamm/laravel-pjax#2]
Woudn't be better to use template that will detect whether to show full page html or only container element?

For example main view:

```
@if (Request::header('X-PJAX'))
    @yield('content')
@else
    @include('layouts.base')
@endif
```

layouts.base view is a main view including full body content.

**Comment by simonstamm** [comment]
Hey daris,

yes, this would be possible in some cases. In addition, this solution has the better perfomance since it's not rendering the whole template.

Regards,
Simon
